"""Runtime version resolution for Loreweaver.

The version is derived automatically from git (see `[tool.setuptools_scm]` in
`pyproject.toml`): it increases with every commit, and milestone versions come from
`v*` tags. This module is the single place every entrypoint (`app.py --version`,
`--doctor`, the frozen PyInstaller bundle) asks "what version am I?" — it never
raises, degrading gracefully down a fallback chain instead.

Resolution order:
  1. `_lw_version` — the module `setuptools-scm` writes at build time (an editable
     dev install or a built wheel). Gitignored; regenerated on every build.
  2. `importlib.metadata.version("loreweaver")` — an installed wheel/sdist whose
     metadata carries the version even without the generated module.
  3. A frozen-build sidecar `VERSION` text file baked in next to the PyInstaller
     bundle's data directory (see `loreweaver-server.spec`) — the only source a
     truly frozen binary has, since it has neither `_lw_version` nor installed
     package metadata.
  4. `FALLBACK_VERSION` — last resort, e.g. a source tarball with no `.git` and no
     installed metadata (the one-click host's source-tarball install tier).
"""

from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

FALLBACK_VERSION = "0.0.0+unknown"


def resolve_version() -> str:
    """Resolve the running Loreweaver's version, trying each source in turn."""
    for source in (_from_scm_module, _from_installed_metadata, _from_frozen_sidecar):
        version = source()
        if version:
            return version
    return FALLBACK_VERSION


def _from_scm_module() -> str | None:
    try:
        import _lw_version  # generated by setuptools-scm at build time; gitignored
    except ImportError:
        return None
    return getattr(_lw_version, "__version__", None) or getattr(_lw_version, "version", None)


def _from_installed_metadata() -> str | None:
    try:
        return metadata.version("loreweaver")
    except metadata.PackageNotFoundError:
        return None


def _from_frozen_sidecar() -> str | None:
    """A `VERSION` text file baked in next to the frozen bundle's data directory —
    written at build time by `loreweaver-server.spec`."""
    if not getattr(sys, "frozen", False):
        return None
    base = getattr(sys, "_MEIPASS", None)
    if not base:
        return None
    try:
        text = (Path(base) / "VERSION").read_text(encoding="utf-8").strip()
    except OSError:
        return None
    return text or None
