"""M18 — the campaign chronicle, deterministic core.

Worldbook = what the AUTHOR wrote (static lore). Chronicle = what the TABLE did
(emergent history). The two stores never mix; they meet only in retrieval.

This module holds the deterministic half of the milestone (`docs/specs/
M18-campaign-chronicle.md`): the three document types' projections and write
validation, the fold hysteresis levels, batch selection, and the no-future
guard. The generative half (the fold LLM call) lives in `agent.chronicle`.

Three document types, all built on the M17 substrate:

- ``chronicle`` — per-scene/stretch narrative records written as play proceeds.
  The narrative ``text`` is table-public (it records what HAPPENED); keeper
  spoiler annotations (what players MISSED, which secret consequences are now
  armed) live in the ``keeper`` field and never cross ``project()``. Each entry
  carries ``turn`` — the index of the turn it was written after. Entries are
  PAST-only records: the recorder tool accepts no turn parameter, so nothing
  can be written speculatively ahead of the fiction.
- ``campaign_summary`` — ONE rolling "story so far" singleton at a fixed char
  budget, regenerated by folding the oldest entries in. Its ``keeper`` margin
  is keeper-editable and keeper-only; the player projection backs `.recap`.
- ``thread`` — the open-loops tracker (planted foreshadowing, unresolved hooks,
  armed consequences): ``{label, status: open|resolved, notes}``. Keeper-only
  whole-document (fail-closed like ``note``): an open loop may be a secret the
  players have not discovered yet. Only ``status`` is structured so the engine
  can nag about stale loops; everything else stays free-form (kp_note doctrine).

The fold policy (owner-resolved, tuned for narrative economics — narration
summarizes far more gracefully than code, and a game re-sends context every
turn):

- **trigger**: assembled-prompt fullness ≥ 0.60 of the room model's window → fold
  (read from the per-turn `usage_stats` accounting — a reactive meter, the
  provider's own count where the endpoint reports one and `agent.loop`'s
  flagged estimate of the same prompt where it does not);
- **floor**: fold oldest-first in batches until the projection ≤ 0.40 — batch
  folding, never one-entry-per-turn churn;
- **emergency**: ≥ 0.85 → fold before the next model call, so the
  fold-generation call itself always has headroom;
- **no-future guard**: entries with ``turn`` beyond the watermark
  (``current_turn - lag_turns``, default lag 4) are never fold candidates — the
  in-flight scene is not summarizable history yet — and a fold input referencing
  turns beyond the watermark is rejected engine-side (`validate_fold_input`).
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # no runtime import of core.documents — documents.py imports US
    from core.documents import Document, Viewer

CHRONICLE_DOC_TYPE = "chronicle"
CAMPAIGN_SUMMARY_DOC_TYPE = "campaign_summary"
THREAD_DOC_TYPE = "thread"
CAMPAIGN_SUMMARY_ID = "summary"

THREAD_STATUSES = frozenset({"open", "resolved"})

# Player-projection field allowlists. Everything else on the document — the
# ``keeper`` annotation margin, fold bookkeeping (``folded``/``tokens``/
# ``fold_count``) — is keeper-side by construction (iron rule #3).
_CHRONICLE_PLAYER_FIELDS = ("text", "turn", "pcs", "scene")
_SUMMARY_PLAYER_FIELDS = ("text", "through_turn")


# ---------------------------------------------------------------------------
# Projections (registered in core.documents' built-in table)
# ---------------------------------------------------------------------------


def project_chronicle(doc: Document, viewer: Viewer) -> dict[str, Any] | None:
    """Chronicle entry: the keeper sees everything; every player-grade viewer
    gets the public narrative record (text/turn/PC tags/scene) — never the
    keeper annotations, never the fold bookkeeping."""
    if viewer.is_keeper:
        return dict(doc.data)
    return {key: doc.data[key] for key in _CHRONICLE_PLAYER_FIELDS if key in doc.data}


def project_campaign_summary(doc: Document, viewer: Viewer) -> dict[str, Any] | None:
    """Rolling summary: players get the spoiler-free "previously on…" (text +
    coverage watermark); the keeper margin stays keeper-side."""
    if viewer.is_keeper:
        return dict(doc.data)
    return {key: doc.data[key] for key in _SUMMARY_PLAYER_FIELDS if key in doc.data}


def project_thread(doc: Document, viewer: Viewer) -> dict[str, Any] | None:
    """Open loops are keeper-only, whole-document: a planted hook's very
    existence can be a spoiler (fail-closed, same posture as `note`)."""
    return dict(doc.data) if viewer.is_keeper else None


# ---------------------------------------------------------------------------
# Write validation
# ---------------------------------------------------------------------------


def validate_chronicle_write(doc: Document, services: Any) -> list[str]:
    violations = []
    text = doc.data.get("text")
    if not isinstance(text, str) or not text.strip():
        violations.append("text must be a non-empty string")  # i18n-exempt: validation diagnostic, not UI text
    turn = doc.data.get("turn")
    if isinstance(turn, bool) or not isinstance(turn, int) or turn < 0:
        violations.append(
            "turn must be a non-negative integer (the turn the entry was written after)"  # i18n-exempt: diagnostic
        )
    if not isinstance(doc.data.get("keeper", ""), str):
        violations.append("keeper must be a string")  # i18n-exempt: validation diagnostic
    pcs = doc.data.get("pcs", [])
    if not isinstance(pcs, list) or any(not isinstance(pc, str) for pc in pcs):
        violations.append("pcs must be a list of character names")  # i18n-exempt: validation diagnostic
    return violations


def validate_campaign_summary_write(doc: Document, services: Any) -> list[str]:
    violations = []
    if not isinstance(doc.data.get("text"), str) or not doc.data.get("text", "").strip():
        violations.append("text must be a non-empty string")  # i18n-exempt: validation diagnostic
    for field_name in ("through_turn", "fold_count"):
        value = doc.data.get(field_name)
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            violations.append(f"{field_name} must be a non-negative integer")  # i18n-exempt: diagnostic
    if not isinstance(doc.data.get("keeper", ""), str):
        violations.append("keeper must be a string")  # i18n-exempt: validation diagnostic
    return violations


def validate_thread_write(doc: Document, services: Any) -> list[str]:
    violations = []
    if not isinstance(doc.data.get("label"), str) or not doc.data.get("label", "").strip():
        violations.append("label must be a non-empty string")  # i18n-exempt: validation diagnostic
    if doc.data.get("status") not in THREAD_STATUSES:
        violations.append(
            f"status must be one of: {', '.join(sorted(THREAD_STATUSES))}"  # i18n-exempt: diagnostic
        )
    if not isinstance(doc.data.get("notes", ""), str):
        violations.append("notes must be a string")  # i18n-exempt: validation diagnostic
    return violations


def thread_id_for(label: str) -> str:
    """A thread's stable document id, derived from its label so the KP agent can
    upsert by name without scanning (and re-stating a loop updates, never dupes)."""
    digest = hashlib.sha1(label.strip().casefold().encode("utf-8")).hexdigest()[:10]
    return f"t-{digest}"


# ---------------------------------------------------------------------------
# Token estimation + the fold policy (pure functions)
# ---------------------------------------------------------------------------


def estimate_tokens(text: str) -> int:
    """A rough, deterministic token estimate for fold accounting.

    The codebase's budgets are char-based and the fullness meter is MEASURED
    (provider-reported prompt tokens), so this only ever sizes chronicle
    content itself. CJK ideographs/punctuation run ~1 token per character while
    latin prose runs ~4 chars per token — a flat chars/4 rule would under-count
    a Chinese campaign's records four-fold and fold far too late.
    """
    if not text:
        return 0
    cjk = sum(1 for ch in text if _is_cjk(ch))
    other = len(text) - cjk
    return max(1, cjk + (other + 3) // 4)


def _is_cjk(ch: str) -> bool:
    code = ord(ch)
    return (
        0x2E80 <= code <= 0x9FFF  # CJK radicals, Kangxi, Extension A, Unified Ideographs
        or 0x3000 <= code <= 0x303F  # CJK punctuation
        or 0xFF00 <= code <= 0xFFEF  # fullwidth forms
        or 0xF900 <= code <= 0xFAFF  # compatibility ideographs
    )


def fold_watermark(current_turn: int, lag_turns: int) -> int:
    """The no-future watermark: only entries with ``turn <= watermark`` are
    foldable, so the trailing ``lag_turns`` turns always stay raw."""
    return current_turn - lag_turns


def fold_decision(fullness: float, *, trigger: float, emergency: float) -> str:
    """The hysteresis levels: "none" | "fold" | "emergency"."""
    if fullness >= emergency:
        return "emergency"
    if fullness >= trigger:
        return "fold"
    return "none"


@dataclass(frozen=True)
class FoldCandidate:
    """One foldable chronicle entry, reduced to what the fold policy needs."""

    id: str
    turn: int
    tokens: int


def select_fold_batch(
    candidates: list[FoldCandidate],
    *,
    watermark: int,
    max_entries: int,
) -> list[FoldCandidate]:
    """One fold batch: eligible entries (at/below the watermark), oldest first,
    capped at `max_entries`. The caller iterates batches — one fold call never
    consumes an unbounded backlog.

    HOW MANY records to fold is deliberately NOT decided here. It depends on what
    the prompt's chronicle SECTION renders, which is agent-side knowledge (the
    renderer, its caps and its locale); this function only decides which records
    are eligible and in what order. It used to take a `needed_free_tokens` deficit
    and accumulate `candidate.tokens` until it was covered — sizing in a unit the
    section's render caps falsify, since a record the tail never renders costs the
    prompt nothing to keep and frees nothing when folded."""
    eligible = sorted((c for c in candidates if c.turn <= watermark), key=lambda c: (c.turn, c.id))
    return eligible[:max_entries]


def validate_fold_input(batch: list[FoldCandidate], *, watermark: int) -> list[str]:
    """The engine-side no-future guard: a fold whose input references turn
    indices beyond the watermark is rejected. Batch selection is already
    structurally past-only; this is the defense-in-depth check that runs on the
    actual fold input right before the generation call (不许写未来)."""
    return [
        f"chronicle entry {candidate.id} references turn {candidate.turn}, beyond the fold watermark {watermark}"
        for candidate in batch
        if candidate.turn > watermark
    ]
